/*
package com.ninestar.coolweather;

public class test {
    {"HeWeather":[
        {
            "basic":
            {"cid":"CN101010200","location":"海淀","parent_city":"北京","admin_area":"北京","cnty":"中国","lat":"38.46636963","lon":"106.27817535","tz":"+8.00","city":"海淀","id":"CN101010200",
                    "update":{"loc":"2020-04-21 15:14","utc":"2020-04-21 07:14"}
            },
            "update":{"loc":"2020-04-21 15:14","utc":"2020-04-21 07:14"},
            "status":
                "ok",
             "now":
            {"cloud":"10","cond_code":"101","cond_txt":"多云","fl":"7","hum":"13","pcpn":"0.0","pres":"1020","tmp":"10","vis":"8","wind_deg":"294","wind_dir":"西北风","wind_sc":"2","wind_spd":"7","cond":
                {"code":"101","txt":"多云"}
            },
            "daily_forecast":
			[
            {"date":"2020-04-22","cond":
                {"txt_d":"多云"},"tmp":
                {"max":"13","min":"-2"}
            },
            {"date":"2020-04-23","cond":
                {"txt_d":"多云"},"tmp":
                {"max":"10","min":"-2"}
            },
            {"date":"2020-04-24","cond":
                {"txt_d":"晴"},"tmp":
                {"max":"11","min":"1"}
            },
            {"date":"2020-04-25","cond":
                {"txt_d":"阴"},"tmp":
                {"max":"14","min":"-1"}
            },
            {"date":"2020-04-26","cond":
                {"txt_d":"多云"},"tmp":
                {"max":"15","min":"2"}
            },
            {"date":"2020-04-27","cond":
                {"txt_d":"晴"},"tmp":
                {"max":"11","min":"3"}
            }
			],
         "aqi":
            {"city":
            {"aqi":"86","pm25":"18","qlty":"良"}
        },
            "suggestion":
            {"comf":
                {"type":"comf","brf":"较舒适","txt":"白天天气晴好但风力较强，早晚会感觉偏凉，午后舒适、宜人。"},"sport":
                {"type":"sport","brf":"较适宜","txt":"天气较好，但考虑风力较强且气温较低，推荐您进行室内运动，若在户外运动注意防风并适当增减衣物。"},"cw":
                {"type":"cw","brf":"较不宜","txt":"较不宜洗车，未来一天无雨，风力较大，如果执意擦洗汽车，要做好蒙上污垢的心理准备。"}
            },"msg":"所有天气数据均为模拟数据，仅用作学习目的使用，请勿当作真实的天气预报软件来使用。"
        }
		]
    }
}
*/
